Vagrant.configure(2) do |config|
  config.vm.define "elk" do |elk|
    elk.vm.box = "ubuntu/xenial64"
    elk.ssh.insert_key = 'false'
    elk.vm.hostname = "elk.swiftstack.org"
    elk.vm.network "private_network", ip: "192.168.22.201"
    elk.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
    elk.vm.provision "shell", path: "elk.sh"
    elk.vm.synced_folder "git/", "/home/ubuntu/git", create: true
    end
  end
end
